/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsWorkflowAutomationRouteImport } from './routes/projects.workflow-automation'
import { Route as ProjectsMobileOrderingRouteImport } from './routes/projects.mobile-ordering'
import { Route as ProjectsErpRouteImport } from './routes/projects.erp'
import { Route as ProjectsDesignSystemRouteImport } from './routes/projects.design-system'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsWorkflowAutomationRoute =
  ProjectsWorkflowAutomationRouteImport.update({
    id: '/projects/workflow-automation',
    path: '/projects/workflow-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsMobileOrderingRoute = ProjectsMobileOrderingRouteImport.update({
  id: '/projects/mobile-ordering',
  path: '/projects/mobile-ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsErpRoute = ProjectsErpRouteImport.update({
  id: '/projects/erp',
  path: '/projects/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDesignSystemRoute = ProjectsDesignSystemRouteImport.update({
  id: '/projects/design-system',
  path: '/projects/design-system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/design-system': typeof ProjectsDesignSystemRoute
  '/projects/erp': typeof ProjectsErpRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/design-system': typeof ProjectsDesignSystemRoute
  '/projects/erp': typeof ProjectsErpRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/design-system': typeof ProjectsDesignSystemRoute
  '/projects/erp': typeof ProjectsErpRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/design-system'
    | '/projects/erp'
    | '/projects/mobile-ordering'
    | '/projects/workflow-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/design-system'
    | '/projects/erp'
    | '/projects/mobile-ordering'
    | '/projects/workflow-automation'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/design-system'
    | '/projects/erp'
    | '/projects/mobile-ordering'
    | '/projects/workflow-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsDesignSystemRoute: typeof ProjectsDesignSystemRoute
  ProjectsErpRoute: typeof ProjectsErpRoute
  ProjectsMobileOrderingRoute: typeof ProjectsMobileOrderingRoute
  ProjectsWorkflowAutomationRoute: typeof ProjectsWorkflowAutomationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/workflow-automation': {
      id: '/projects/workflow-automation'
      path: '/projects/workflow-automation'
      fullPath: '/projects/workflow-automation'
      preLoaderRoute: typeof ProjectsWorkflowAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mobile-ordering': {
      id: '/projects/mobile-ordering'
      path: '/projects/mobile-ordering'
      fullPath: '/projects/mobile-ordering'
      preLoaderRoute: typeof ProjectsMobileOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/erp': {
      id: '/projects/erp'
      path: '/projects/erp'
      fullPath: '/projects/erp'
      preLoaderRoute: typeof ProjectsErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/design-system': {
      id: '/projects/design-system'
      path: '/projects/design-system'
      fullPath: '/projects/design-system'
      preLoaderRoute: typeof ProjectsDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsDesignSystemRoute: ProjectsDesignSystemRoute,
  ProjectsErpRoute: ProjectsErpRoute,
  ProjectsMobileOrderingRoute: ProjectsMobileOrderingRoute,
  ProjectsWorkflowAutomationRoute: ProjectsWorkflowAutomationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
