/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsOperationalErpRouteImport } from './routes/projects.operational-erp'
import { Route as ProjectsMobileOrderingRouteImport } from './routes/projects.mobile-ordering'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOperationalErpRoute = ProjectsOperationalErpRouteImport.update({
  id: '/projects/operational-erp',
  path: '/projects/operational-erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMobileOrderingRoute = ProjectsMobileOrderingRouteImport.update({
  id: '/projects/mobile-ordering',
  path: '/projects/mobile-ordering',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/operational-erp': typeof ProjectsOperationalErpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/operational-erp': typeof ProjectsOperationalErpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/mobile-ordering': typeof ProjectsMobileOrderingRoute
  '/projects/operational-erp': typeof ProjectsOperationalErpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/mobile-ordering'
    | '/projects/operational-erp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/mobile-ordering'
    | '/projects/operational-erp'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/mobile-ordering'
    | '/projects/operational-erp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsMobileOrderingRoute: typeof ProjectsMobileOrderingRoute
  ProjectsOperationalErpRoute: typeof ProjectsOperationalErpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/operational-erp': {
      id: '/projects/operational-erp'
      path: '/projects/operational-erp'
      fullPath: '/projects/operational-erp'
      preLoaderRoute: typeof ProjectsOperationalErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mobile-ordering': {
      id: '/projects/mobile-ordering'
      path: '/projects/mobile-ordering'
      fullPath: '/projects/mobile-ordering'
      preLoaderRoute: typeof ProjectsMobileOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsMobileOrderingRoute: ProjectsMobileOrderingRoute,
  ProjectsOperationalErpRoute: ProjectsOperationalErpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
